<h3>Coming soon</h3>
<p>
  <ul>
    <li>
      <b>C. doughertyi (awaiting upload; Blaxter Lab assembly)</b>
    </li>
    <li>
      <b>C. tropicalis (awaiting upload; WormBase assembly)</b>
    </li>
    <li>
      <b>C. sp. 21 (in assembly; Blaxter Lab)</b>
    </li>
    <li>
      <b>C. sp. 26 (in assembly; Blaxter Lab)</b>
    </li>
    <li>
      <b>C. sp. 31 (in assembly; Blaxter Lab)</b>
    </li>
    <li>
      <b>C. guadeloupensis (in assembly; Blaxter Lab)</b>
    </li>
    <li>
      <b>C. castelli (in assembly; Blaxter Lab)</b>
    </li>
    <li>
      <b>C. plicata (in assembly; Blaxter Lab)</b>
    </li>
    <li>
      <b>C. sp. 39 (in assembly; Blaxter Lab; raw data is poor quality however)</b>
    </li>
    <li>
      <b>C. sp. 43 (in assembly; Blaxter Lab; raw data is poor quality however)</b>
    </li>
    <li>
      <b>C. macrosperma (in assembly; Cutter Lab)</b>
    </li>
    <li>
      <b>C. nouraguensis (in assembly; Janet Young)</b>
    </li>
  </ul>
</p>
