<h3>Coming soon</h3>
<p>
  <ul>
    <li>
      <b>C. doughertyi</b> (awaiting upload; Blaxter Lab assembly)
    </li>
    <li>
      <b>C. tropicalis</b> (awaiting upload; WormBase assembly)
    </li>
    <li>
      <b>C. sp. 21</b> (in assembly; Blaxter Lab)
    </li>
    <li>
      <b>C. sp. 26</b> (in assembly; Blaxter Lab)
    </li>
    <li>
      <b>C. sp. 31</b> (in assembly; Blaxter Lab)
    </li>
    <li>
      <b>C. guadeloupensis</b> (in assembly; Blaxter Lab)
    </li>
    <li>
      <b>C. castelli</b> (in assembly; Blaxter Lab)
    </li>
    <li>
      <b>C. plicata</b> (in assembly; Blaxter Lab)
    </li>
    <li>
      <b>C. sp. 39</b> (in assembly; Blaxter Lab; raw data is poor quality however)
    </li>
    <li>
      <b>C. sp. 43</b> (in assembly; Blaxter Lab; raw data is poor quality however)
    </li>
    <li>
      <b>C. macrosperma</b> (in assembly; Cutter Lab)
    </li>
    <li>
      <b>C. nouraguensis</b> (in assembly; Janet Young)
    </li>
  </ul>
</p>
