<h3>Coming soon</h3>
<p>
  <ul>
    <li>
      <b>C. sp. 34 (long-read assembly currently in progress, Tasei Kikuchi <em>et al.</em>)</b>
    </li>
    <li>
      <b>C. nigoni (long-read assembly currently in progress, Erich Schwarz)</b>
    </li>
    <li>
      <b>C. tropicalis (long-read reassembly currently in progress, Erich Schwarz)</b>
    </li>
    <li>
      <b>C. wallacei (long-read assembly currently in progress, Erich Schwarz)</b>
    </li>
  </ul>
</p>
