<h3>Other genomes</h3>
<p>
  <ul>
    <li>
      <b>C. sp. 34</b> (long-read assembly currently in progress, Tasei Kikuchi <em>et al.</em>)
    </li>
    <li>
      <b>C. nigoni</b> (long-read assembly currently in progress, Erich Schwarz)
    </li>
    <li>
      <b>C. tropicalis</b> (long-read reassembly currently in progress, Erich Schwarz)
    </li>
    <li>
      <b>C. wallacei</b> (long-read assembly currently in progress, Erich Schwarz)
    </li>
  </ul>
</p>
